# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MeetUp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MeetUp
   pod 'Parse'
   pod 'AlamofireImage'

  target 'MeetUpTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MeetUpUITests' do
    # Pods for testing
  end

end
